on: [push, pull_request]

name: Build & test - parallel jobs with cache

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          # use action built on top of actions/cache with less configuration
          # caching on .toml here since this is a library, but generally better to do it on the .lock file
          shared-key: ${{ hashFiles('**/Cargo.toml') }}
      - run: cargo build

  # this job will run after build job and download the build cache
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ hashFiles('**/Cargo.toml') }}
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ hashFiles('**/Cargo.toml') }}
      - run: cargo clippy -- -D warnings